Feat/simplify search n filter
near/neardevhub-widgets pull request #125
Opened 2023-05-09 23:18 UTC by ben-jamming-reilly

2023-05-19 11:49 UTC, frol commented on src/gigs-board/components/layout/SearchByAuthor.jsx
> +      // style="position: absolute; inset: 0px auto auto 0px; display: block; max-height: 300px; overflow: auto; transform: translate3d(0px, 38px, 0px); width: 160px;"
I feel that this is still a draft PR given that there are some commented-out parts in the code.

2023-05-19 13:48 UTC, frol requested changes

2023-05-19 13:48 UTC, frol commented on src/gigs-board/components/layout/Controls.jsx
> +      href="gigs-board.pages.Create"
Use `href` helper (see https://github.com/near/neardevhub-widgets/pull/122#discussion_r1198920006 for more details)

2023-05-19 13:48 UTC, frol commented on src/gigs-board/components/layout/Controls.jsx
> +      Submit Idea / Solution
Can we make the search inputs and this button to be on the same line?

<img width="1329" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/f5a2be9c-70c6-4631-860b-7719c6610fba">

2023-05-19 13:50 UTC, frol commented on src/gigs-board/pages/Create.jsx
> +/* INCLUDE: "common.jsx" */
Just so everyone is on the same page, it seems we cannot merge this PR without #122.

2023-05-20 01:45 UTC, ben-jamming-reilly commented
My benreilly.near widgets were out of date. Here is the current version
[Video](https://www.loom.com/share/6d5a93c096f348b89c7a90f23f17e808)

Below is the update widgets with both the new search and create post experience
[Test](https://near.org/benreilly.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=benreilly.near)

2023-05-30 21:08 UTC, frol commented
It seems that all the changes were done in #122 and this PR only had an incomplete implementation of `customMenu` on the `SearchByAuthor` component, so I am closing this PR.

2023-05-30 21:08 UTC, closed without merging