210-revert-142
near/neardevhub-widgets pull request #215
Opened 2023-07-28 13:22 UTC by Tguntenaar

2023-07-28 14:18 UTC, ailisp commented on src/gigs-board/pages/Create.jsx
> +  postType: "",
This should be unchanged otherwise it cause bug #213

2023-07-28 14:29 UTC, ailisp commented
PR looks good overall. The description isn't accurate, this PR intends to address #142 without introduce bugs. The acceptance criteria is
> Expected behavior

 > User should see the same fields & preview in the solution reply as shown in the create solution post
    User should be able to select USDC and proceed successfully without a warning message

As i tested these criteria are met, so just ensure address above comments to avoid introduce a bug.

2023-08-03 01:08 UTC, ailisp requested changes
Please address above comment to avoid introduce #213

2023-08-10 00:39 UTC, ailisp commented
@Tguntenaar I just update the title and acceptance criteria to make this PR's purpose accurate

2023-08-16 03:00 UTC, ailisp commented
Reply solution post doesn't include the "yes and no" section. Also please merge main branch and resolve conflict. Now main branch has only USDT and NEAR as currency.

2023-09-04 09:51 UTC, Tguntenaar commented
@ailisp The preview is probably showing the wrong version. Something with the bos cli blocks me from pushing the components to mainnet.

2023-09-07 08:15 UTC, ailisp commented
There are some bugs during my testing, list here for checking after fix:
- [ ] reply with sponsorship type, specify NEAR token gives this error:
<img width="543" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/bff5de52-2169-41bd-b68c-668db10c7e6f">
- [ ] reply with solution type, specify USDT token renders preview and result post with "[object object]:
<img width="371" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/60314c79-1ddd-41dd-8d98-210691e3f58e">

Below are correct cases, but need ensure it's still work after fix the above two issues.
- [ ] reply with sponsorship type, specify USDT token works fine. 
- [ ] reply with solution type, specify NEAR token works fine.
- [ ] create solution post with NEAR or USDT token work fine.

2023-09-11 15:40 UTC, Tguntenaar commented
- [x] reply with sponsorship type, specify NEAR token no longer gives error
- [x] reply with solution type, specify USDT token renders preview and result post correct

Below are correct cases, but need ensure it's still work after fix the above two issues.

- [ ] reply with sponsorship type, specify USDT token works fine.
- [ ] reply with solution type, specify NEAR token works fine.
- [ ] create solution post with NEAR or USDT token work fine.

2023-09-12 17:25 UTC, Tguntenaar commented
Hi @ailisp,

Finally tested all cases, they all work. I think it is ready to merge.

2023-09-13 04:24 UTC, ailisp commented
@Tguntenaar Mainnet preview no longer works, can you push a new one?

Testnet preview has some bugs:
- reply with a solution, when requested sponsor is empty, the requested fund doesn't show up:
<img width="566" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/f5e0ad43-ff99-426f-b01f-07612e1eb358">

- reply with a solution, enter the requested sponsor, and leave token as default (NEAR), but the transaction shows USDT:
<img width="933" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/5b530b05-8bdb-4e01-a2a2-0d92f1fb9fc2">

2023-09-13 21:29 UTC, Tguntenaar commented
Hi @ailisp,

> reply with a solution, when requested sponsor is empty, the requested fund doesn't show up

This was intented it is the same behaviour as the Create widget. (Create a solution post and remove the requested sponsorship field) We could change it in both places. What would be the desired behaviour? A warning before submission that sponsorship is required or did you have something else in mind. 

> reply with a solution, enter the requested sponsor, and leave token as default (NEAR), but the transaction shows USDT

That is strange.. I didn't and don't experience this. It is probably caused by the snapshot of the state. I will try to reproduce the behaviour and come up with a solution.

2023-09-14 03:37 UTC, ailisp commented
OK! Sounds great then. I also tested on mainnet and the NEAR shown as USDT problem doesn't exist. For sponsorship empty it's not a new problem introduced in this PR, we might want to address in a separate ticket. Now all tests work fine. Could you please resolve conflict so we can merge it?

2023-09-14 03:37 UTC, ailisp approved these changes

2023-09-15 02:27 UTC, merged