feature: introduces better markdown functionality for posts #221
near/neardevhub-widgets pull request #232
Opened 2023-08-08 23:27 UTC by elliotBraem

Makes changes to post form to feature a more powerful markdown editor

_Resolves https://github.com/near/neardevhub-widgets/issues/221_

2023-08-09 05:24 UTC, elliotBraem commented
Acceptance Criteria:

- [x] Text editor for posts in feed, view [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
- [x] Creator for ideas/solutions, view [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Create?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
- [x] Wiki editor for communities, view [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.community.new?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
- [x] Live previews are still visible below as they were before.
- [x] Line breaks format on separate lines.


Notes:
- Checkboxes are a custom implementation and there are some known inconsistencies:
    - the <Markdown> component in the VM renders checkboxes with a prepended bullet (may be undesirable?)
    - pressing enter for a new line after creating a checkbox does not create another checkbox (like on github). This should be possible, but requires some more savvy development... will see if I can resolve)
- "Reference to other [thing]" is the icon to the far right. It will write "bos://" to text and relies on this [PR to the VM](https://github.com/NearSocial/VM/pull/90/commits) to be merged before working. But once it works, we can embed widgets and other things.
- The full SimpleMDE widget can be found [here](https://near.social/devhub.efiz.near/widget/SimpleMDE). You can see all of the available functionalities and the line/word counter in the bottom right. Let me know if any of these should be incorporated into DevHub. Icons can be interchanged with the icons found [here](https://fontawesome.com/v4/icons/).
- This was a larger story than I anticipated :)

2023-08-09 07:49 UTC, carina-akaia requested changes

2023-08-09 07:49 UTC, carina-akaia commented on src/gigs-board/components/organism/editor.jsx
> +    className: "px-2"
Let's remove this class and pass it only in particular cases when it's really needed

2023-08-09 07:49 UTC, carina-akaia commented on src/gigs-board/components/organism/editor.jsx
> +                className: fieldParamsByType[fieldType].className + " w-100",
See the previous comment

2023-08-10 20:45 UTC, elliotBraem commented
After finishing the development for posts and applying it to community pages, I'd like to move community page editor to a separate PR for #178. Community pages (Wiki + Bio) has some additional pieces to it that require more attention.

You can see the current work [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.community.new?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near), but notice how the label does not show up. This will require some thinking.

Otherwsie, this PR is ready for review.

2023-08-11 06:21 UTC, ailisp commented on src/gigs-board/components/molecule/markdown-editor.jsx
> +            "quote",
Tried out every format hear. Majority of them looks great. The `quote` style, doesn't look obvious that it means to quote something:
<img width="350" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/cc07996f-3a96-4130-885e-2271855dd541">

Can we tweak the style a little bit?

2023-08-11 06:22 UTC, ailisp commented on src/gigs-board/components/molecule/markdown-editor.jsx
> +            "mention",
mention used to have an auto-completion. Is it possible to keep that?
<img width="1220" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/037cd529-b01f-49f5-b15e-aa86cec89b6a">

2023-08-11 06:22 UTC, ailisp approved these changes
Looks great! And code is very clean and neat!

2023-08-16 02:47 UTC, ailisp commented
Mention looks good, but quote still looks like just bigger sized text:
<img width="228" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/42612e35-ca08-4f10-8ff3-c0e062ca450d">

<img width="254" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/dbbb9ffc-2aca-4531-885c-6b2f8a64cefa">

Is it possible to make it looks like github quote:
<img width="89" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/8b32b5ad-4be8-4836-8058-8390d8cc5cef">

2023-09-05 22:33 UTC, elliotBraem commented
This is ready for merge now @ailisp @ori-near

2023-09-05 22:35 UTC, ori-near commented
Thanks @elliotBraem – what link should I use to see the latest preview?

2023-09-06 17:04 UTC, ori-near commented
Hi @elliotBraem, thanks so much for posting this. Overall looks great. Here are few suggestions I found. I would say number 1 is the most important. We can create a separate ticket for any of the other ones if they're not quick fixes. Thank you.

**1: Line Breaks**
Entering separate line breaks do not render that way. Instead, they concatenate.
![Screenshot 2023-09-06 at 9 49 57 AM](https://github.com/near/neardevhub-widgets/assets/110252255/f5b187a2-c5c4-4d26-a9fd-0d65ab8082e0)

**2: URLS**
Clicking on the URL icon shows `[](http://)`. Could we change that to `[](https://)`? Also, it seems like when I just enter www.devhub.org the URL doesn't work. 

**3: @ Handles**
When I click or type the @ handle, once I start typing text such as `Ell`, I see the the list of suggested names. When I click Elliot, the description only shows `Ell` but the preview shows the full name. Once a user is selected, can we show the full name also in the description?
![Screenshot 2023-09-06 at 9 56 07 AM](https://github.com/near/neardevhub-widgets/assets/110252255/d744b3b0-9c4e-4442-943d-d96a26ec7e0e)

**4: Quotes**
Right now quote CSS displays the text as larger, which makes it hard to distinguish. Is there a way to style quote text similar to how GitHub or Gmail displays them:
![Screenshot 2023-09-06 at 9 58 39 AM](https://github.com/near/neardevhub-widgets/assets/110252255/153b3f7d-d5ec-48d6-b80d-10290a959678)

**5: Code Block**
Could we style code blocks inside a gray box or something, to help make it visually different from other text?
![Screenshot 2023-09-06 at 10 01 03 AM](https://github.com/near/neardevhub-widgets/assets/110252255/870e5c2f-7d77-4bdc-a9a2-3c0125ecfd52)

**6: Reference Thing**
What's the purpose of the reference thing? I wasn't sure actually how to use it. Do we need it?

2023-09-07 02:17 UTC, elliotBraem commented
🤦 

Check out the below, how's this?

![Screenshot 2023-09-06 at 9 20 41 PM](https://github.com/near/neardevhub-widgets/assets/16282460/03b70dbc-0fb4-46aa-92d2-f3f5f61e8c02)

The only one I had trouble with was mentions... which was definitely a crazy ride to figure out -- but we did it! I can deploy a preview again, but I currently have #245 deployed -- I can do again after that's merged if you'd like.

As for "reference thing", I have removed the button for now, but when we move to the social contract, we can enable some really cool functionalities like how we reference pull requests and commits on Github... and so many other things 😄

2023-09-07 09:06 UTC, ailisp commented
Code looks pretty good! From the screenshot I can see a lot of points from Ori is addressed and the remaining points at least you seem to tested them (for 1,2 and 3). Given this PR has been blocked by other PRs for quite long I'm going to merge it.

2023-09-07 09:06 UTC, merged

2023-09-07 11:00 UTC, ailisp commented
Double checked in production, everything points from Ori is addressed! Great work!