a few search and sort enhancements
near/neardevhub-widgets pull request #327
Opened 2023-10-20 07:53 UTC by ailisp

Fix #324, Fix #314 
Also make search instantly trigger when typing, instead of pressing enter to search.

2023-10-22 10:21 UTC, frol requested changes
> After "Sort -> All replies" then search will search all comments and posts

This is not really intuitive since it is not "sorting". I guess you may want to rename it to "filter" and default would be "Top-level posts".

There is also a bug: the state of this dropdown is not displayed after selection.

2023-10-22 10:24 UTC, frol commented
Another bug related to #314 - tags filtering does not work when you click on a tag of a post (see #226) it was previously resolved, but it is an issue again.

2023-10-23 02:07 UTC, ailisp commented
@frol 

> This is not really intuitive since it is not "sorting". I guess you may want to rename it to "filter" and default would be "Top-level posts".

I have the same feeling here, your proposed way is more intuitive to me, but this is trying to match original design: 
<img width="188" alt="image" src="https://github.com/near/neardevhub-widgets/assets/13259400/cfa4b00f-4b4d-4afc-a2d6-eb70b021d368">

(Sorting by hottest is WIP in indexer side). Let's come back to consider it after getting it matches to the design.

I'll fix these ones:

> There is also a bug: the state of this dropdown is not displayed after selection. 
> Another bug related to https://github.com/near/neardevhub-widgets/issues/314 - tags filtering does not work when you click on a tag of a post (see https://github.com/near/neardevhub-widgets/issues/226) it was previously resolved, but it is an issue again.

2023-10-25 06:17 UTC, frol approved these changes
All the reported issues are addressed and this PR looks good to me

2023-10-25 06:17 UTC, frol commented on src/gigs-board/feature/post-search/panel.jsx
> +console.log(state.tag);
Remove the debug logs

2023-10-25 08:24 UTC, merged